backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: src/assets/images # Location where files will be stored in the repo
public_folder: src/assets/images  # The src attribute for uploaded media
site_url: https://christianmetalarchives.com  # Displays a link to home page in the top-right corner of the CMS dashboard

collections:
  - name: "death-metal" # Used in routes, e.g., /admin/collections/blog
    label: "death-metal" # Used in the UI
    folder: "src/content/death-metal" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Band", name: "band", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Status", name: "status", widget: "string" }
      - { label: "Genre", name: "genre", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }      