backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: src/assets/images # Location where files will be stored in the repo
public_folder: src/assets/images  # The src attribute for uploaded media
site_url: https://christianmetalarchives.com  # Displays a link to home page in the top-right corner of the CMS dashboard

collections:
  - name: "death-metal" # Used in routes, e.g., /admin/collections/blog
    label: "death-metal" # Used in the UI
    folder: "src/content/deathmetal" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Band", name: "band", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Country of Origin", name: "country", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Formed In", name: "formed", widget: "string" }
      - { label: "Status", name: "status", widget: "string" }
      - { label: "Genre", name: "genre", widget: "string" }
      - { label: "Themes", name: "themes", widget: "string" }
      - { label: "Current Label", name: "currentLabel", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Band Members", name: "bandMembers", widget: "markdown" }    
      - { label: "Discography", name: "discography", widget: "markdown" }     

  - name: "deathcore" # Used in routes, e.g., /admin/collections/blog
    label: "deathcore" # Used in the UI
    folder: "src/content/deathcore" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Band", name: "band", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Country of Origin", name: "country", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Formed In", name: "formed", widget: "string" }
      - { label: "Status", name: "status", widget: "string" }
      - { label: "Genre", name: "genre", widget: "string" }
      - { label: "Themes", name: "themes", widget: "string" }
      - { label: "Current Label", name: "currentLabel", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Band Members", name: "bandMembers", widget: "markdown" }    
      - { label: "Discography", name: "discography", widget: "markdown" }  